#!/bin/bash -e

vagrant ssh master -c "
sudo dnf install -y http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm &&
sudo dnf install -y ovirt-provider-ovn &&
sudo bash -c 'cat <<EOF > /etc/ovirt-provider-ovn/conf.d/kubernetes.conf
[SSL]
https-enabled=false
[OVN REMOTE]
ovn-remote=127.0.0.1:6641
[AUTH]
auth-plugin=auth.plugins.static_token:NoAuthPlugin
EOF' &&
sudo systemctl restart ovirt-provider-ovn
"
