#!/bin/bash -e

sudo vagrant ssh master -c "sudo dnf install -y python"
master_ip=$(sudo vagrant ssh master -c "python -c 'import socket, sys; sys.stdout.write(socket.gethostbyname(socket.gethostname()))'")

vagrant ssh master -c "
sudo dnf install -y openvswitch-ovn-central &&
sudo systemctl enable ovn-northd &&
sudo systemctl restart ovn-northd &&
sudo ovn-sbctl set-connection ptcp:6642 &&
sudo ovn-nbctl set-connection ptcp:6641
"

FAIL=0

HOSTS=( node1 node2 )
for node in "${HOSTS[@]}"; do
    (
        sudo vagrant ssh $node -c "sudo dnf install -y python" &&
        node_ip=$(sudo vagrant ssh $node -c "python -c 'import socket, sys; sys.stdout.write(socket.gethostbyname(socket.gethostname()))'") &&
        vagrant ssh $node -c "
sudo dnf install -y openvswitch-ovn-host &&
sudo systemctl start openvswitch &&
sudo ovs-vsctl set open . external-ids:ovn-remote=tcp:${master_ip}:6642 &&
sudo ovs-vsctl set open . external-ids:ovn-encap-type=geneve &&
sudo ovs-vsctl set open . external-ids:ovn-encap-ip=${node_ip} &&
sudo systemctl enable openvswitch &&
sudo systemctl enable ovn-controller &&
sudo systemctl restart openvswitch &&
sudo systemctl restart ovn-controller
        "
    ) &
done

for job in $(jobs -p); do
    echo $job
    wait $job || let "FAIL+=1"
done

if [ "$FAIL" != "0" ]; then
    echo "Nodes installation failed $FAIL times"
    exit 1
fi
