#!/bin/bash -e

ssh -i id_rsa vagrant@192.168.200.11 "
sudo yum install -y http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm ;
sudo yum install -y openvswitch-ovn-central &&
sudo systemctl enable ovn-northd &&
sudo systemctl restart ovn-northd &&
sudo ovn-sbctl set-connection ptcp:6642 &&
sudo ovn-nbctl set-connection ptcp:6641
"

FAIL=0

NODE_IPS=( 192.168.200.11 192.168.200.12 192.168.200.13 )
for node_ip in "${NODE_IPS[@]}"; do
    (
        ssh -i id_rsa vagrant@$node_ip "
sudo yum install -y http://resources.ovirt.org/pub/yum-repo/ovirt-release-master.rpm ;
sudo yum install -y openvswitch-ovn-host &&
sudo systemctl start openvswitch &&
sudo ovs-vsctl set open . external-ids:ovn-remote=tcp:192.168.200.11:6642 &&
sudo ovs-vsctl set open . external-ids:ovn-encap-type=geneve &&
sudo ovs-vsctl set open . external-ids:ovn-encap-ip=${node_ip} &&
sudo systemctl enable openvswitch &&
sudo systemctl enable ovn-controller &&
sudo systemctl restart openvswitch &&
sudo systemctl restart ovn-controller
        "
    ) &
done

for job in $(jobs -p); do
    echo $job
    wait $job || let "FAIL+=1"
done

if [ "$FAIL" != "0" ]; then
    echo "Nodes installation failed $FAIL times"
    exit 1
fi
