#!/bin/bash -x

KUBECTL=./hack/kubectl
ADMISSION_IMAGE=${ADMISSION_IMAGE:-phoracek/kubetron-admission:latest}
DEVICEPLUGIN_IMAGE=${DEVICEPLUGIN_IMAGE:-phoracek/kubetron-deviceplugin:latest}

ADMISSION_CERT=$(cat server.crt | base64 -w 0)
ADMISSION_KEY=$(cat hack/server-key.pem | base64 -w 0)
KUBERNETES_CA=$(ssh -i id_rsa vagrant@192.168.200.11 "sudo cat /etc/kubernetes/ssl/ca.pem" | base64 -w 0)
PROVIDER_URL=http://192.168.200.11:9696

# batch request is not done sequentialy and sometimes it fails with "namespace does not exist",
# therefore, create it beforehand
$KUBECTL create --save-config namespace kubetron
sleep 2

cat deploy/addon.yaml.in | \
    sed "s#\$ADMISSION_IMAGE#$ADMISSION_IMAGE#g" | \
    sed "s#\$DEVICEPLUGIN_IMAGE#$DEVICEPLUGIN_IMAGE#g" | \
    sed "s/\$ADMISSION_CERT/$ADMISSION_CERT/g" | \
    sed "s/\$ADMISSION_KEY/$ADMISSION_KEY/g" | \
    sed "s/\$KUBERNETES_CA/$KUBERNETES_CA/g" | \
    sed "s#\$PROVIDER_URL#$PROVIDER_URL#g" | \
    $KUBECTL apply -f -
