#!/usr/bin/bash -ex

exec > >(tee -ia /var/log/attach-pod.log)
exec 2> >(tee -ia /var/log/attach-pod.err.out)

CONTAINERNAME=$1
PORTNAME=$2
PORTID=$3
MAC=$4
PID=$5

# create internal port on integration bridge, that will be later pased to pod netns
ovs-vsctl -- \
    add-port br-int $PORTNAME -- \
    set Interface $PORTNAME type=internal

sleep 1

# initialize /var/run/netns in case it does not exist yet
ls /var/run/netns || ip netns add dummyNS || true

# we need to create a named netns for given pid, so we are able to use `ip netns`
rm -f /var/run/netns/$CONTAINERNAME
ln -s /host/proc/$PID/ns/net /var/run/netns/$CONTAINERNAME

# move interface to pod netns, configure its MAC and set it up
ip link set dev $PORTNAME netns $CONTAINERNAME
ip netns exec $CONTAINERNAME ip link set $PORTNAME address $MAC
ip netns exec $CONTAINERNAME ip link set $PORTNAME up

# finally mark interface with its interface ID, so it is recognized by OVN
ovs-vsctl set Interface $PORTNAME external_ids:iface-id=$PORTID

# TODO: call dhcp ipam via cni
