#!/usr/bin/env python3

import json
import os
import shutil

MULTUS_BIN_SOURCE = '/opt/multus'
MULTUS_BIN_DESTINATION = '/opt/cni/bin/multus'

KUBETRON_BIN_SOURCE = '/opt/kubetron'
KUBETRON_BIN_DESTINATION = '/opt/cni/bin/kubetron'

CNI_NETWORK_CONFIGS_DIR = '/etc/cni/net.d/'

MULTUS_NETWORK_CONFIG_FILE = CNI_NETWORK_CONFIGS_DIR + '00-multus.conf'


def main():
    # TODO: use atomic copy
    shutil.copyfile(MULTUS_BIN_SOURCE, MULTUS_BIN_DESTINATION)
    shutil.copyfile(KUBETRON_BIN_SOURCE, KUBETRON_BIN_DESTINATION)

    networkConfigFile = sorted([
        os.path.join(CNI_NETWORK_CONFIGS_DIR, f)
        for f in os.listdir(CNI_NETWORK_CONFIGS_DIR)])[0]
    with open(networkConfigFile) as f:
        networkConfig = json.load(f)

    if networkConfig['type'] == 'multus':
        # TODO: make sure kubetron is there
    else:
        # TODO: add primaryplugin to original
        # TODO: create multus with kubetron and original
        # TODO: save it
    # read existing config
    # if multus, check that contains kubetron
    # else, move existing to multus with kubetron


if __name__ == '__main__':
    main()
